<?php 
$countries = array(
'AF' => array('name'=> 'Afghanistan', 'dCode' => '93'),
'AX' => array('name'=> 'Aland Islands', 'dCode' => '358'),
'AL' => array('name'=> 'Albania', 'dCode' => '355'),
'DZ' => array('name'=> 'Algeria', 'dCode' => '213'),
'AS' => array('name'=> 'American Samoa', 'dCode' => '1'),
'AD' => array('name'=> 'Andorra', 'dCode' => '376'),
'AO' => array('name'=> 'Angola', 'dCode' => '244'),
'AI' => array('name'=> 'Anguilla', 'dCode' => '1'),
// 'AQ' => array('name'=> 'Antarctica', 'dCode' => ''),
'AG' => array('name'=> 'Antigua And Barbuda', 'dCode' => '1'),
'AR' => array('name'=> 'Argentina', 'dCode' => '54'),
'AM' => array('name'=> 'Armenia', 'dCode' => '374'),
'AW' => array('name'=> 'Aruba', 'dCode' => '297'),
'AU' => array('name'=> 'Australia', 'dCode' => '61'),
'AT' => array('name'=> 'Austria', 'dCode' => '43'),
'AZ' => array('name'=> 'Azerbaijan', 'dCode' => '994'),
'BS' => array('name'=> 'Bahamas', 'dCode' => '1'),
'BH' => array('name'=> 'Bahrain', 'dCode' => '973'),
'BD' => array('name'=> 'Bangladesh', 'dCode' => '880'),
'BB' => array('name'=> 'Barbados', 'dCode' => '1'),
'BY' => array('name'=> 'Belarus', 'dCode' => '375'),
'BE' => array('name'=> 'Belgium', 'dCode' => '32'),
'BZ' => array('name'=> 'Belize', 'dCode' => '501'),
'BJ' => array('name'=> 'Benin', 'dCode' => '229'),
'BM' => array('name'=> 'Bermuda', 'dCode' => '1'),
'BT' => array('name'=> 'Bhutan', 'dCode' => '975'),
'BO' => array('name'=> 'Bolivia', 'dCode' => '591'),
'BA' => array('name'=> 'Bosnia And Herzegovina', 'dCode' => '387'),
'BW' => array('name'=> 'Botswana', 'dCode' => '267'),
// 'BV' => array('name'=> 'Bouvet Island', 'dCode' => ''),
'BR' => array('name'=> 'Brazil', 'dCode' => '55'),
// 'IO' => array('name'=> 'British Indian Ocean Territory', 'dCode' => ''),
'BN' => array('name'=> 'Brunei Darussalam', 'dCode' => '673'),
'BG' => array('name'=> 'Bulgaria', 'dCode' => '359'),
'BF' => array('name'=> 'Burkina Faso', 'dCode' => '226'),
'BI' => array('name'=> 'Burundi', 'dCode' => '257'),
'KH' => array('name'=> 'Cambodia', 'dCode' => '855'),
'CM' => array('name'=> 'Cameroon', 'dCode' => '237'),
'CA' => array('name'=> 'Canada', 'dCode' => '1'),
'CV' => array('name'=> 'Cape Verde', 'dCode' => '238'),
'KY' => array('name'=> 'Cayman Islands', 'dCode' => '1'),
'CF' => array('name'=> 'Central African Republic', 'dCode' => '236'),
'TD' => array('name'=> 'Chad', 'dCode' => '235'),
'CL' => array('name'=> 'Chile', 'dCode' => '56'),
'CN' => array('name'=> 'China', 'dCode' => '86'),
// 'CX' => array('name'=> 'Christmas Island', 'dCode' => ''),
'CC' => array('name'=> 'Cocos (Keeling) Islands', 'dCode' => '61'),
'CO' => array('name'=> 'Colombia', 'dCode' => '57'),
'KM' => array('name'=> 'Comoros', 'dCode' => '269'),
'CG' => array('name'=> 'Congo - Brazzaville', 'dCode' => '242'),
'CD' => array('name'=> 'Congo - Kinshasa', 'dCode' => '243'),
'CK' => array('name'=> 'Cook Islands', 'dCode' => '682'),
'CR' => array('name'=> 'Costa Rica', 'dCode' => '506'),
'CI' => array('name'=> 'Cote D\'Ivoire', 'dCode' => '225'),
'CW' => array('name'=> 'Curaçao', 'dCode' => '599'),
'HR' => array('name'=> 'Croatia', 'dCode' => '385'),
// 'CU' => array('name'=> 'Cuba', 'dCode' => ''),
'CY' => array('name'=> 'Cyprus', 'dCode' => '357'),
'CZ' => array('name'=> 'Czech Republic', 'dCode' => '420'),
'DK' => array('name'=> 'Denmark', 'dCode' => '45'),
'DJ' => array('name'=> 'Djibouti', 'dCode' => '253'),
'DM' => array('name'=> 'Dominica', 'dCode' => '1'),
'DO' => array('name'=> 'Dominican Republic', 'dCode' => '1'),
'EC' => array('name'=> 'Ecuador', 'dCode' => '593'),
'EG' => array('name'=> 'Egypt', 'dCode' => '20'),
'SV' => array('name'=> 'El Salvador', 'dCode' => '503'),
'GQ' => array('name'=> 'Equatorial Guinea', 'dCode' => '240'),
'ER' => array('name'=> 'Eritrea', 'dCode' => '291'),
'EE' => array('name'=> 'Estonia', 'dCode' => '372'),
'ET' => array('name'=> 'Ethiopia', 'dCode' => '251'),
'FK' => array('name'=> 'Falkland Islands (Malvinas)', 'dCode' => '500'),
'FO' => array('name'=> 'Faroe Islands', 'dCode' => '298'),
'FJ' => array('name'=> 'Fiji', 'dCode' => '679'),
'FI' => array('name'=> 'Finland', 'dCode' => '358'),
'FR' => array('name'=> 'France', 'dCode' => '33'),
'GF' => array('name'=> 'French Guiana', 'dCode' => '594'),
'PF' => array('name'=> 'French Polynesia', 'dCode' => '689'),
// 'TF' => array('name'=> 'French Southern Territories', 'dCode' => ''),
'GA' => array('name'=> 'Gabon', 'dCode' => '241'),
'GM' => array('name'=> 'Gambia', 'dCode' => '220'),
'GE' => array('name'=> 'Georgia', 'dCode' => '995'),
'DE' => array('name'=> 'Germany', 'dCode' => '49'),
'GH' => array('name'=> 'Ghana', 'dCode' => '233'),
'GI' => array('name'=> 'Gibraltar', 'dCode' => '350'),
'GR' => array('name'=> 'Greece', 'dCode' => '30'),
'GL' => array('name'=> 'Greenland', 'dCode' => '299'),
'GD' => array('name'=> 'Grenada', 'dCode' => '1'),
'GP' => array('name'=> 'Guadeloupe', 'dCode' => '590'),
'GU' => array('name'=> 'Guam', 'dCode' => '1'),
'GT' => array('name'=> 'Guatemala', 'dCode' => '502'),
'GG' => array('name'=> 'Guernsey', 'dCode' => '44'),
'GN' => array('name'=> 'Guinea', 'dCode' => '224'),
'GW' => array('name'=> 'Guinea-Bissau', 'dCode' => '245'),
'GY' => array('name'=> 'Guyana', 'dCode' => '592'),
'HT' => array('name'=> 'Haiti', 'dCode' => '509'),
// 'HM' => array('name'=> 'Heard Island & Mcdonald Islands', 'dCode' => ''),
// 'VA' => array('name'=> 'Holy See (Vatican City State)', 'dCode' => ''),
'HN' => array('name'=> 'Honduras', 'dCode' => '504'),
'HK' => array('name'=> 'Hong Kong', 'dCode' => '852'),
'HU' => array('name'=> 'Hungary', 'dCode' => '36'),
'IS' => array('name'=> 'Iceland', 'dCode' => '354'),
'IN' => array('name'=> 'India', 'dCode' => '91'),
'ID' => array('name'=> 'Indonesia', 'dCode' => '62'),
// 'IR' => array('name'=> 'Iran, Islamic Republic Of', 'dCode' => ''),
'IQ' => array('name'=> 'Iraq', 'dCode' => '964'),
'IE' => array('name'=> 'Ireland', 'dCode' => '353'),
'IM' => array('name'=> 'Isle Of Man', 'dCode' => '44'),
'IL' => array('name'=> 'Israel', 'dCode' => '972'),
'IT' => array('name'=> 'Italy', 'dCode' => '39'),
'JM' => array('name'=> 'Jamaica', 'dCode' => '1'),
'JP' => array('name'=> 'Japan', 'dCode' => '81'),
'JE' => array('name'=> 'Jersey', 'dCode' => '44'),
'JO' => array('name'=> 'Jordan', 'dCode' => '962'),
'KZ' => array('name'=> 'Kazakhstan', 'dCode' => '7'),
'KE' => array('name'=> 'Kenya', 'dCode' => '254'),
'KI' => array('name'=> 'Kiribati', 'dCode' => '686'),
'KR' => array('name'=> 'South Korea', 'dCode' => '82'),
'KW' => array('name'=> 'Kuwait', 'dCode' => '965'),
'KG' => array('name'=> 'Kyrgyzstan', 'dCode' => '996'),
'LA' => array('name'=> 'Laos', 'dCode' => '856'),
'LV' => array('name'=> 'Latvia', 'dCode' => '371'),
'LB' => array('name'=> 'Lebanon', 'dCode' => '961'),
'LS' => array('name'=> 'Lesotho', 'dCode' => '266'),
'LR' => array('name'=> 'Liberia', 'dCode' => '231'),
// 'LY' => array('name'=> 'Libyan Arab Jamahiriya', 'dCode' => ''),
'LI' => array('name'=> 'Liechtenstein', 'dCode' => '423'),
'LT' => array('name'=> 'Lithuania', 'dCode' => '370'),
'LU' => array('name'=> 'Luxembourg', 'dCode' => '352'),
// 'MO' => array('name'=> 'Macao', 'dCode' => ''),
'MK' => array('name'=> 'Macedonia', 'dCode' => '389'),
'MG' => array('name'=> 'Madagascar', 'dCode' => '261'),
'MW' => array('name'=> 'Malawi', 'dCode' => '265'),
'MY' => array('name'=> 'Malaysia', 'dCode' => '60'),
'MV' => array('name'=> 'Maldives', 'dCode' => '960'),
'ML' => array('name'=> 'Mali', 'dCode' => '223'),
'MT' => array('name'=> 'Malta', 'dCode' => '356'),
// 'MH' => array('name'=> 'Marshall Islands', 'dCode' => ''),
'MQ' => array('name'=> 'Martinique', 'dCode' => '596'),
'MR' => array('name'=> 'Mauritania', 'dCode' => '222'),
'MU' => array('name'=> 'Mauritius', 'dCode' => '230'),
'YT' => array('name'=> 'Mayotte', 'dCode' => '262'),
'MX' => array('name'=> 'Mexico', 'dCode' => '52'),
'FM' => array('name'=> 'Micronesia', 'dCode' => '691'),
'MD' => array('name'=> 'Moldova', 'dCode' => '373'),
'MC' => array('name'=> 'Monaco', 'dCode' => '377'),
'MN' => array('name'=> 'Mongolia', 'dCode' => '976'),
'ME' => array('name'=> 'Montenegro', 'dCode' => '382'),
'MS' => array('name'=> 'Montserrat', 'dCode' => '1'),
'MA' => array('name'=> 'Morocco', 'dCode' => '212'),
'MZ' => array('name'=> 'Mozambique', 'dCode' => '258'),
'MM' => array('name'=> 'Myanmar (Burma)', 'dCode' => '95'),
'NA' => array('name'=> 'Namibia', 'dCode' => '264'),
'NR' => array('name'=> 'Nauru', 'dCode' => '674'),
'NP' => array('name'=> 'Nepal', 'dCode' => '977'),
'NL' => array('name'=> 'Netherlands', 'dCode' => '31'),
'BQ' => array('name'=> 'Caribbean Netherlands', 'dCode' => '599'),
'NC' => array('name'=> 'New Caledonia', 'dCode' => '687'),
'NZ' => array('name'=> 'New Zealand', 'dCode' => '64'),
'NI' => array('name'=> 'Nicaragua', 'dCode' => '505'),
'NE' => array('name'=> 'Niger', 'dCode' => '227'),
'NG' => array('name'=> 'Nigeria', 'dCode' => '234'),
// 'NU' => array('name'=> 'Niue', 'dCode' => ''),
'NF' => array('name'=> 'Norfolk Island', 'dCode' => '672'),
'MP' => array('name'=> 'Northern Mariana Islands', 'dCode' => '1'),
'NO' => array('name'=> 'Norway', 'dCode' => '47'),
'OM' => array('name'=> 'Oman', 'dCode' => '968'),
'PK' => array('name'=> 'Pakistan', 'dCode' => '92'),
// 'PW' => array('name'=> 'Palau', 'dCode' => ''),
'PS' => array('name'=> 'Palestinian Territories', 'dCode' => '970'),
'PA' => array('name'=> 'Panama', 'dCode' => '507'),
'PG' => array('name'=> 'Papua New Guinea', 'dCode' => '675'),
'PY' => array('name'=> 'Paraguay', 'dCode' => '595'),
'PE' => array('name'=> 'Peru', 'dCode' => '51'),
'PH' => array('name'=> 'Philippines', 'dCode' => '63'),
// 'PN' => array('name'=> 'Pitcairn', 'dCode' => ''),
'PL' => array('name'=> 'Poland', 'dCode' => '48'),
'PT' => array('name'=> 'Portugal', 'dCode' => '351'),
'PR' => array('name'=> 'Puerto Rico', 'dCode' => '1'),
'QA' => array('name'=> 'Qatar', 'dCode' => '974'),
'RE' => array('name'=> 'Reunion', 'dCode' => '262'),
'RO' => array('name'=> 'Romania', 'dCode' => '40'),
'RU' => array('name'=> 'Russian Federation', 'dCode' => '7'),
'RW' => array('name'=> 'Rwanda', 'dCode' => '250'),
// 'BL' => array('name'=> 'Saint Barthelemy', 'dCode' => ''),
// 'SH' => array('name'=> 'Saint Helena', 'dCode' => ''),
'KN' => array('name'=> 'Saint Kitts And Nevis', 'dCode' => '1'),
'LC' => array('name'=> 'Saint Lucia', 'dCode' => '1'),
'MF' => array('name'=> 'Saint Martin', 'dCode' => '590'),
// 'PM' => array('name'=> 'Saint Pierre And Miquelon', 'dCode' => ''),
'VC' => array('name'=> 'Saint Vincent And Grenadines', 'dCode' => '1'),
'WS' => array('name'=> 'Samoa', 'dCode' => '685'),
'SM' => array('name'=> 'San Marino', 'dCode' => '378'),
'ST' => array('name'=> 'Sao Tome And Principe', 'dCode' => '239'),
'SA' => array('name'=> 'Saudi Arabia', 'dCode' => '966'),
'SN' => array('name'=> 'Senegal', 'dCode' => '221'),
'RS' => array('name'=> 'Serbia', 'dCode' => '381'),
'SC' => array('name'=> 'Seychelles', 'dCode' => '248'),
'SL' => array('name'=> 'Sierra Leone', 'dCode' => '232'),
'SG' => array('name'=> 'Singapore', 'dCode' => '65'),
'SK' => array('name'=> 'Slovakia', 'dCode' => '421'),
'SI' => array('name'=> 'Slovenia', 'dCode' => '386'),
'SB' => array('name'=> 'Solomon Islands', 'dCode' => '677'),
// 'SO' => array('name'=> 'Somalia', 'dCode' => ''),
'ZA' => array('name'=> 'South Africa', 'dCode' => '27'),
'GS' => array('name'=> 'South Georgia And Sandwich Isl.', 'dCode' => ''),
'ES' => array('name'=> 'Spain', 'dCode' => '34'),
'LK' => array('name'=> 'Sri Lanka', 'dCode' => '94'),
'SD' => array('name'=> 'South Sudan', 'dCode' => '211'),
'SR' => array('name'=> 'Suriname', 'dCode' => '597'),
// 'SJ' => array('name'=> 'Svalbard And Jan Mayen', 'dCode' => ''),
'SZ' => array('name'=> 'Swaziland', 'dCode' => '268'),
'SE' => array('name'=> 'Sweden', 'dCode' => '46'),
'CH' => array('name'=> 'Switzerland', 'dCode' => '41'),
// 'SY' => array('name'=> 'Syrian Arab Republic', 'dCode' => ''),
'TW' => array('name'=> 'Taiwan', 'dCode' => '886'),
'TJ' => array('name'=> 'Tajikistan', 'dCode' => '992'),
'TZ' => array('name'=> 'Tanzania', 'dCode' => '255'),
'TH' => array('name'=> 'Thailand', 'dCode' => '66'),
'TL' => array('name'=> 'Timor-Leste', 'dCode' => '670'),
'TG' => array('name'=> 'Togo', 'dCode' => '228'),
// 'TK' => array('name'=> 'Tokelau', 'dCode' => ''),
'TO' => array('name'=> 'Tonga', 'dCode' => '676'),
'TT' => array('name'=> 'Trinidad And Tobago', 'dCode' => '1'),
'TN' => array('name'=> 'Tunisia', 'dCode' => '216'),
'TR' => array('name'=> 'Turkey', 'dCode' => '90'),
'TM' => array('name'=> 'Turkmenistan', 'dCode' => '993'),
'TC' => array('name'=> 'Turks And Caicos Islands', 'dCode' => '1'),
// 'TV' => array('name'=> 'Tuvalu', 'dCode' => ''),
'UG' => array('name'=> 'Uganda', 'dCode' => '256'),
'UA' => array('name'=> 'Ukraine', 'dCode' => '380'),
'AE' => array('name'=> 'United Arab Emirates', 'dCode' => '971'),
'GB' => array('name'=> 'United Kingdom', 'dCode' => '44'),
'US' => array('name'=> 'United States', 'dCode' => '1'),
// 'UM' => array('name'=> 'United States Outlying Islands', 'dCode' => ''),
'UY' => array('name'=> 'Uruguay', 'dCode' => '598'),
'UZ' => array('name'=> 'Uzbekistan', 'dCode' => '998'),
'VU' => array('name'=> 'Vanuatu', 'dCode' => '678'),
'VE' => array('name'=> 'Venezuela', 'dCode' => '58'),
'VN' => array('name'=> 'Viet Nam', 'dCode' => '84'),
'VG' => array('name'=> 'Virgin Islands, British', 'dCode' => '1'),
'VI' => array('name'=> 'Virgin Islands, U.S.', 'dCode' => '1'),
// 'WF' => array('name'=> 'Wallis And Futuna', 'dCode' => ''),
// 'EH' => array('name'=> 'Western Sahara', 'dCode' => ''),
'YE' => array('name'=> 'Yemen', 'dCode' => '967'),
'ZM' => array('name'=> 'Zambia', 'dCode' => '260'),
'ZW' => array('name'=> 'Zimbabwe', 'dCode' => '263'),
);

?>
